title : Food
author :
  name : Greg Payne
#  email : blah@email.test
  github : stackpr
production_url : https://food.payne.run

# Allow page redirects. See https://help.github.com/articles/redirects-on-github-pages/
gems:
  - jekyll-redirect-from
